wordDict = {
    "_id": "62a56c2a5eae3b1b05baf3d9",
    "word": "estrade",
    "contentProvider": {"name": "wordnik", "id": 711},
    "definitions": [
        {
            "source": "century",
            "text": "An elevated part of the floor of a room; a raised platform or dais.",
            "note": None,
            "partOfSpeech": "noun",
        },
        {
            "source": "gcide",
            "text": "A portion of the floor of a room raised above the general level, as a place for a bed or a throne; a platform; a dais.",
            "note": None,
            "partOfSpeech": "noun",
        },
        {
            "source": "wiktionary",
            "text": "A dais or raised platform.",
            "note": None,
            "partOfSpeech": "noun",
        },
    ],
    "publishDate": "2022-06-12T03:00:00.000Z",
    "examples": [
        {
            "url": "http://etext.library.adelaide.edu.au/b/burton/richard/b97b/complete.html",
            "title": "The Book of The Thousand Nights And A Night",
            "text": "Its door was of Indian teak-wood inlaid with gold that glowed; and through it one passed into a royal-hall in whose midst was a jetting fount girt by a raised estrade.",
            "id": 1099556709,
        },
        {
            "url": "http://etext.library.adelaide.edu.au/b/burton/richard/b97b/complete.html",
            "title": "The Book of The Thousand Nights And A Night",
            "text": "He made her no answer: so she came down from the bed on the estrade; and catching hold of his skirt laid it on her head and kissed his feet, saying, “Veil what Allah veileth!”",
            "id": 1099593088,
        },
        {
            "url": "http://etext.library.adelaide.edu.au/b/burton/richard/b97b/complete.html",
            "title": "The Book of The Thousand Nights And A Night",
            "text": "They then visited every part of the gardens and ate of the fruits and continued walking till it waxed dark, when they returned to the estrade and sat down, Janshah on the throne in the centre and the three others on the stools ranged to the right and left.",
            "id": 1099568964,
        },
        {
            "url": "http://etext.library.adelaide.edu.au/b/burton/richard/b97b/complete.html",
            "title": "The Book of The Thousand Nights And A Night",
            "text": "The estrade at the upper end was hung and carpeted with brocaded silks of various colours and thereon stood two thrones of red gold, inlaid with pearls and jewels.",
            "id": 1099587776,
        },
        {
            "url": "http://etext.library.adelaide.edu.au/b/bronte/charlotte/b869pr/complete.html",
            "title": "The Professor, by Charlotte Bronte",
            "text": "The three I allude to were just in front, within half a yard of my estrade, and were among the most womanly-looking present.",
            "id": 997582151,
        },
        {
            "url": "http://etext.library.adelaide.edu.au/b/bronte/charlotte/b869pr/complete.html",
            "title": "The Professor, by Charlotte Bronte",
            "text": "Probably I should not have troubled myself to do so, had I been full in front; but I observed that she immediately began to slip her books into her cabas again; and, presently, after I had returned to the estrade, while I was arranging the mass of compositions, I heard the folding-door again open and close; and, on looking up, I perceived her place vacant.",
            "id": 997582611,
        },
        {
            "url": "http://etext.library.adelaide.edu.au/b/bronte/charlotte/b869v/b869v.html",
            "title": "Villette",
            "text": "Monsieur curled his lip, gave me a vicious glance of the eye, and strode to his estrade.",
            "id": 1095271805,
        },
        {
            "url": "http://etext.library.adelaide.edu.au/b/bronte/charlotte/b869v/b869v.html",
            "title": "Villette",
            "text": "Gathering an armful of his books out of my desk, I filled my apron and poured them in a heap upon his estrade, at his feet.",
            "id": 1095274147,
        },
        {
            "url": "http://www.gutenberg.org/dirs/2/7/5/1/27514/27514-8.txt",
            "title": "A Handful of Stars Texts That Have Moved Great Minds",
            "text": "Suddenly a slim, alert figure leaped upon the estrade and struck the desk sharply with a baton.",
            "id": 1127316781,
        },
        {
            "title": "The Three Brontes",
            "text": "Beside Heathcliff, that Titan raging on a mountain-top, M. Paul is merely a little man gesticulating on an estrade.",
            "id": 1034333297,
        },
        {
            "url": "http://www.gutenberg.org/dirs/1/3/9/5/13955/13955-8.txt",
            "title": "The Sunny Side of Diplomatic Life, 1875-1912",
            "text": "As soon as I could, I approached the Queen, who was sitting in one of the gilded chairs on the _estrade_ which does duty for a throne, and told her of Nina's engagement.",
            "id": 1178598118,
        },
    ],
    "pdd": "2022-06-12",
    "note": "The word 'estrade' comes originally from a Latin word meaning 'bed covering'.",
    "htmlExtra": None,
}
